[functions."Odds-API"]
verify_jwt = false

[functions."paystack-banks"]
verify_jwt = false

[functions."resolve-bank-account"]
verify_jwt = false

[functions."create-withdrawal-request"]
verify_jwt = false
