[functions."Odds-API"]
verify_jwt = false

[functions."paystack-banks"]
verify_jwt = false

[functions."resolve-bank-account"]
verify_jwt = false

[functions."create-withdrawal-request"]
verify_jwt = false

[functions."paystack-direct-debit-init"]
verify_jwt = false

[functions."paystack-direct-debit-webhook"]
verify_jwt = false

[functions."auto-topup-check"]
verify_jwt = false

[functions."odds-scores-sync"]
verify_jwt = false

[functions."place-bet"]
verify_jwt = false
